### ISSUE TITLE
Cannot Access BfRt Python CLI Through bfshell

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/meta-mion-sde#12]
Bringing up the `bf_switchd` process drops the caller into the Barefoot Shell (`bfshell`). There is an option (`bfrt_python`) at the top-level context to access Barefoot Runtime commands via Python.

An attempt to enter this mode results in the following error:

```
bfshell> bfrt_python
Traceback (most recent call last):
  File "/usr/lib/python3.4/bfrtcli.py", line 3, in <module>
    from traitlets.config import Config
  File "/usr/lib/python3.4/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/usr/lib/python3.4/traitlets/traitlets.py", line 57, in <module>
    import six
  File "/usr/lib/python3.4/six.py", line 631, in <module>
    import struct
  File "/usr/lib/python3.4/struct.py", line 13, in <module>
    from _struct import *
ImportError: No module named '_struct'
Failed to load bfrtcli python library
bfrt_cli_cmd:197 could not initialize bf_rt for the cli. err: 1
```

**Comment by CommitThis** [comment]
As of 2nd June 2021, this issue still exists.

**Comment by toganlabs** [comment]
I'll take a look at this over the next two weeks.

**Comment by arikachen** [comment]
I have install bfrtcli in stratum docker image. It is works.
1. install python3.8
```
apt install wget build-essential libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
wget https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tgz
tar xvf Python-3.8.13.tgz
cd Python-3.8.13
./configure --enable-optimizations --prefix=/usr
make altinstall
ln -s /usr/bin/python3.8 /usr/bin/python3
pip3.8 install traitlets IPython tabulate netaddr
```
2. cp bfrtcli to stratum container
```
cd $SDE/pkgsrc/bf-drivers/src/bf_rt/bf_rt_python
docker cp bfrtcli.py stratum:/usr/lib/python3.8/
docker cp bfrtInfo.py stratum:/usr/lib/python3.8/
docker cp bfrtLearn.py stratum:/usr/lib/python3.8/
docker cp bfrtTableEntry.py stratum:/usr/lib/python3.8/
docker cp bfrtTable.py stratum:/usr/lib/python3.8/
```
